import { ApiProperty, ApiPropertyOptional, PickType } from '@nestjs/swagger';
import {
  IsInt,
  IsNotEmpty,
  IsOptional,
  IsString,
  IsUrl,
} from 'class-validator';
import { PageRequestDto } from 'src/utils/dto/page.dto';

export class PromotionBannerDTO {
  @IsInt()
  @IsOptional()
  @ApiProperty({
    example: 1,
    description: 'Promotion Banner ID (autogenerated)',
  })
  id?: number;

  @IsString()
  @IsNotEmpty()
  @ApiProperty({
    example: 'https://example.com/image.jpg',
    description: 'Image URL',
  })
  image: string;

  @IsString()
  @IsOptional()
  @IsUrl({}, { message: 'link_url must be a valid URL' })
  @ApiPropertyOptional({
    example: 'https://example.com',
    description: 'Optional redirect URL',
  })
  link_url?: string;
}

export class CreatePromotionBannerDto extends PickType(PromotionBannerDTO, [
  'image',
  'link_url',
]) {}
export class UpdatePromotionBannerDto extends PickType(PromotionBannerDTO, [
  'image',
  'link_url',
]) {}

export class FindAllPromotionBannersDto extends PageRequestDto {
  @IsString()
  @IsOptional()
  @ApiPropertyOptional({
    example: 'https://example.com/image.jpg',
    description: 'Search by image URL',
  })
  image?: string;

  @IsString()
  @IsOptional()
  @ApiPropertyOptional({
    example: 'https://example.com',
    description: 'Search by link URL',
  })
  link_url?: string;

  @IsString()
  @IsOptional()
  @ApiPropertyOptional({
    example: 'search keyword',
    description: 'Keyword search for image or link_url',
  })
  keyword?: string;
}
