import { ApiProperty, PickType } from '@nestjs/swagger';
import { IsInt, IsNotEmpty, IsOptional, IsString } from 'class-validator';

export class CategoryDTO {
  @IsInt()
  @IsOptional()
  @ApiProperty({ example: 1, description: 'Category ID (autogenerated)' })
  id?: number;

  @IsString()
  @IsNotEmpty()
  @ApiProperty({ example: 'Technology', description: 'Category name' })
  name: string;

  @IsString()
  @IsNotEmpty()
  @ApiProperty({ example: 'technology', description: 'Category slug' })
  slug: string;

  @IsInt()
  @IsOptional()
  @ApiProperty({ example: 2, description: 'Parent category ID (optional)' })
  parent_id?: number;
}

export class CreateCategoryDto extends PickType(CategoryDTO, [
  'name',
  'slug',
  'parent_id',
]) {}

export class UpdateCategoryDto extends PickType(CategoryDTO, [
  'name',
  'slug',
  'parent_id',
]) {}
