import { ApiProperty, ApiPropertyOptional, PickType } from '@nestjs/swagger';
import {
  ArrayNotEmpty,
  IsArray,
  isArray,
  IsInt,
  IsNotEmpty,
  IsOptional,
  IsString,
} from 'class-validator';
import { PageRequestDto } from 'src/utils/dto/page.dto';

export class CategoryDTO {
  @IsInt()
  @IsOptional()
  @ApiProperty({ example: 1, description: 'Category ID (autogenerated)' })
  id?: number;

  @IsString()
  @IsNotEmpty()
  @ApiProperty({ example: 'Technology', description: 'Category name' })
  name: string;

  @IsString()
  @IsNotEmpty()
  @ApiProperty({ example: 'technology', description: 'Category slug' })
  slug: string;

  @IsInt()
  @IsOptional()
  @ApiProperty({ example: 2, description: 'Parent category ID (optional)' })
  parent_id?: number;
}

export class DeleteBulkCategoryDto {
  @ApiProperty({
    type: [Number],
    example: [1, 2, 3],
    description: 'Array of category IDs to delete',
  })
  @IsArray()
  @ArrayNotEmpty()
  @IsInt({ each: true })
  ids: number[];
}

export class FindAllCategoriesDto extends PageRequestDto {
  @IsString()
  @IsOptional()
  @ApiPropertyOptional({ example: 'Nama kategori' })
  name?: string;

  @IsString()
  @IsOptional()
  @ApiPropertyOptional({ example: 'kata kunci pencarian' })
  keyword?: string;
}

export class CreateCategoryDto extends PickType(CategoryDTO, [
  'name',
  'slug',
  'parent_id',
]) {}

export class UpdateCategoryDto extends PickType(CategoryDTO, [
  'name',
  'slug',
  'parent_id',
]) {}
