import { ApiProperty, ApiPropertyOptional, PickType } from '@nestjs/swagger';
import { IsInt, IsNotEmpty, IsOptional, IsString } from 'class-validator';
import { PageRequestDto } from 'src/utils/dto/page.dto';

export class TagDTO {
  @IsInt()
  @IsOptional()
  @ApiProperty({ example: 1, description: 'Tag ID (autogenerated)' })
  id?: number;

  @IsString()
  @IsNotEmpty()
  @ApiProperty({ example: 'JavaScript', description: 'Tag name' })
  name: string;

  @IsString()
  @IsNotEmpty()
  @ApiProperty({ example: 'javascript', description: 'Tag slug' })
  slug: string;
}

export class CreateTagDto extends PickType(TagDTO, ['name', 'slug']) {}
export class UpdateTagDto extends PickType(TagDTO, ['name', 'slug']) {}
export class FindAllTagsDto extends PageRequestDto {
  @IsString()
  @IsOptional()
  @ApiPropertyOptional({ example: 'Nama tag' })
  name?: string;

  @IsString()
  @IsOptional()
  @ApiPropertyOptional({ example: 'slug-tag' })
  slug?: string;

  @IsString()
  @IsOptional()
  @ApiPropertyOptional({ example: 'kata kunci pencarian' })
  keyword?: string;
}
