import { ApiProperty, PickType } from '@nestjs/swagger';
import { IsInt, IsNotEmpty, IsOptional, IsString } from 'class-validator';

export class TagDTO {
  @IsInt()
  @IsOptional()
  @ApiProperty({ example: 1, description: 'Tag ID (autogenerated)' })
  id?: number;

  @IsString()
  @IsNotEmpty()
  @ApiProperty({ example: 'JavaScript', description: 'Tag name' })
  name: string;

  @IsString()
  @IsNotEmpty()
  @ApiProperty({ example: 'javascript', description: 'Tag slug' })
  slug: string;
}

export class CreateTagDto extends PickType(TagDTO, ['name', 'slug']) {}
export class UpdateTagDto extends PickType(TagDTO, ['name', 'slug']) {}
