import { ApiProperty, ApiPropertyOptional, PickType } from '@nestjs/swagger';
import {
  IsInt,
  IsNotEmpty,
  IsOptional,
  IsString,
  //   IsUrl,
} from 'class-validator';
import { PageRequestDto } from 'src/utils/dto/page.dto';

export class GameDTO {
  @IsInt()
  @IsOptional()
  @ApiProperty({ example: 1, description: 'Game ID (autogenerated)' })
  id?: number;

  @IsString()
  @IsNotEmpty()
  @ApiProperty({ example: 'Counter Strike', description: 'Game name' })
  name: string;

  @IsString()
  @IsNotEmpty()
  @ApiProperty({
    example: 'https://example.com/image.jpg',
    description: 'Game image URL',
  })
  image: string;

  @IsString()
  @IsNotEmpty()
  @ApiProperty({
    example: 'https://example.com/banner.jpg',
    description: 'Game banner URL',
  })
  banner: string;
}

export class CreateGameDto extends PickType(GameDTO, [
  'name',
  'image',
  'banner',
]) {}
export class UpdateGameDto extends PickType(GameDTO, [
  'name',
  'image',
  'banner',
]) {}

export class FindAllGamesDto extends PageRequestDto {
  @IsString()
  @IsOptional()
  @ApiPropertyOptional({ example: 'Counter Strike' })
  name?: string;

  @IsString()
  @IsOptional()
  @ApiPropertyOptional({ example: 'keyword pencarian game' })
  keyword?: string;
}
